version: '3'
services:
        web:
                build: .
                #map port between container and host
                ports:
                        - 3000:80
                volumes:
                        - .:/home/web
                command: rails new . --database=postgresql

        db:
                image: postgres
                environment:
                        - POSTGRES_PASSWORD = cuongkb3g
                        - POSTGRES_USER     = admin
                
