#!/bin/bash
#this script is used to install dependencies and rails on machine
#for god, just run 1 time only.

apt-get update -y
apt-get install nodejs -y
apt-get install postgresql -y
apt-get install libsqlite3-dev -y
apt-get install sqlite3 -y
apt-get install ruby -y
#dependency nokogiri for rails
apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev -y
gem install rails

#create project
rails new -f web --database=postgresql
cd ./web/
bundle install 

