default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5  } %>
<<<<<<< HEAD
=======
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
>>>>>>> 3d2d42ecba11fc48249a9fe355b3d58d5a5e4c37
  host: <%= ENV['POSTGRES_URL'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test

production:
  <<: *default
  database: webapp_production
