default: &default
  adapter: postgresql
  encoding: unicode
<<<<<<< HEAD
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5  } %>
=======
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
>>>>>>> 12582d3c88f886450ce713d197b45b69d68693ea
  host: <%= ENV['POSTGRES_URL'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test

production:
  <<: *default
  database: webapp_production
